<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_PT Dwidata Talenta Prima_logo</name>
   <tag></tag>
   <elementGuidId>5e17181a-84c1-4cb2-964e-c104149cf8fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='header']/div/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.logo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f843ddab-3619-4cbf-ae45-451e9d31c09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>de1c4580-24c9-4b5c-b49c-9d9e8507a689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d2f3dnusg0rbp7.cloudfront.net/snap/assets/close-button-ae5078c33cdb801c630ab3c2d0926d3456b949b0f39a2ad192743131227e6d41.svg</value>
      <webElementGuid>7974a620-a8a7-400b-a1a8-da7ece1d6e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>d3955761-ff3d-4805-81f2-f8c14d5bad37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;title-bar&quot;]/div[@class=&quot;close-snap-button clickable&quot;]/img[@class=&quot;logo&quot;]</value>
      <webElementGuid>37a42161-8e77-40a3-8cf2-f9edcd12b194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Payment/iframe_concat(id(, , snap-midtrans, , ))_po_ef147f</value>
      <webElementGuid>7b8427dd-93c5-433f-902f-0b75de05dfd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='header']/div/div[2]/img</value>
      <webElementGuid>8a31fde5-c7b9-4ac8-9b39-bbb815ed0f1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='close']</value>
      <webElementGuid>0f61fb8a-bf59-4abf-aa08-10d5fc069dc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>f328482d-d7e3-469f-8aea-d7df556310a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d2f3dnusg0rbp7.cloudfront.net/snap/assets/close-button-ae5078c33cdb801c630ab3c2d0926d3456b949b0f39a2ad192743131227e6d41.svg' and @alt = 'close']</value>
      <webElementGuid>5d87543e-cafc-443c-8c80-0c8d7fd60eff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
