<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cancel                                   _4e9978</name>
   <tag></tag>
   <elementGuidId>1e466797-3df7-42d8-9c5c-748ddd3a320d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cancelButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cancelButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a27b86ca-f8af-42ae-ae41-77fef61a7908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>EVN30012300018/cancel</value>
      <webElementGuid>d597b67d-b5e8-4d4d-9ec9-ab7f7c238b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger btn-icon icon-left</value>
      <webElementGuid>fdbe04f2-263b-42a8-a787-e1c29978f90d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cancelButton</value>
      <webElementGuid>b95eba7d-f584-44ba-ba2c-4aad2cea3a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Cancel
                                            Invoice</value>
      <webElementGuid>5f040260-dbc4-40ef-8a2b-677e62fb3a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cancelButton&quot;)</value>
      <webElementGuid>224daa0d-5eaf-4efd-ab64-6f52aa8883b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cancelButton']</value>
      <webElementGuid>b029ba15-b582-425e-b58b-6039fe8b1d00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/section/div/div/div/div/div[3]/div[3]/div/ul/a[2]</value>
      <webElementGuid>3606c564-04fe-44c1-b66c-8ed370c2638d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Cancel
                                            Invoice')]</value>
      <webElementGuid>75556b83-ea3e-498d-8999-73833d7daee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Complete your payment here :'])[1]/following::a[2]</value>
      <webElementGuid>8bd309d7-483d-4d74-bb5f-e9099df4fc91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoice Date :'])[1]/following::a[2]</value>
      <webElementGuid>4a87701a-cdce-45fa-b3e8-ac7f2e836db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Summary'])[1]/preceding::a[1]</value>
      <webElementGuid>977c3067-5495-48e2-a200-a5cb217f8f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All items here cannot be deleted'])[1]/preceding::a[1]</value>
      <webElementGuid>6c35a401-4fab-4a73-a9ae-6ac60ffdfb45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'EVN30012300018/cancel')]</value>
      <webElementGuid>6f051767-6a6d-44fc-b3fc-041d04c073cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>96e82600-67d8-420c-b76c-8f864bdf4b28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'EVN30012300018/cancel' and @id = 'cancelButton' and (text() = ' Cancel
                                            Invoice' or . = ' Cancel
                                            Invoice')]</value>
      <webElementGuid>38939a9e-97ac-4f87-af3d-072b564693ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
